import React from 'react'
import { Footer } from '@/components/Footer'
import { Header } from '@/components/Header'
import { Inter } from 'next/font/google'
import './globals.css'
import styles from './page.module.css'
import PropTypes from 'prop-types'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <Header/>
        <div className={styles.Page__Children}>
        {children}
        </div>
        <Footer/>
      </body>
    </html>
  )
}
RootLayout.propTypes = {
  children: PropTypes.node.isRequired
}
